#!/bin/sh

set -e

[ -f /etc/default/v-collect ] && . /etc/default/v-collect

IS_UPGRADE=false

case "$1" in
	configure)
	[ -z "$V_USER" ] && V_USER="v"
	[ -z "$V_GROUP" ] && V_GROUP="v"
	if ! getent group "$V_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$V_GROUP" --quiet
	fi
	if ! id $V_USER > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/v-collect --no-create-home \
		--ingroup "$V_GROUP" --disabled-password --shell /bin/false "$V_USER"
	fi

	# Set user permissions on /var/log/v-collect, /var/lib/v-collect
	mkdir -p /var/log/v-collect /var/lib/v-collect
	chown -R $V_USER:$V_GROUP /var/log/v-collect /var/lib/v-collect
	chmod 755 /var/log/v-collect /var/lib/v-collect

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp -r /usr/share/v-collect/conf /etc/v-collect/
  fi

	# configuration files should not be modifiable by v user, as this can be a security issue
	chown -Rh root:$V_GROUP /etc/v-collect/*
	chmod 755 /etc/v-collect
	find /etc/v-collect -type f -exec chmod 640 {} ';'
	find /etc/v-collect -type d -exec chmod 755 {} ';'

  # If $1=configure and $2 is set, this is an upgrade
  if [ "$2" != "" ]; then
    IS_UPGRADE=true
  fi

  if [ "x$IS_UPGRADE" != "xtrue" ]; then
    if command -v systemctl >/dev/null; then
      echo "### NOT starting on installation, please execute the following statements to configure v-collect to start automatically using systemd"
      echo " sudo /bin/systemctl daemon-reload"
      echo " sudo /bin/systemctl enable v-collect"
      echo "### You can start v-collect by executing"
      echo " sudo /bin/systemctl start v-collect"
    elif command -v update-rc.d >/dev/null; then
      echo "### NOT starting v-collect by default on bootup, please execute"
      echo " sudo update-rc.d v-collect defaults 95 10"
      echo "### In order to start v-collect, execute"
      echo " sudo service v-collect start"
    fi
  elif [ "$RESTART_ON_UPGRADE" = "true" ]; then

    echo -n "Restarting v-collect service..."

    if command -v systemctl >/dev/null; then
      systemctl daemon-reload
      systemctl restart v-collect || true
    elif [ -x /etc/init.d/v-collect ]; then
      if command -v invoke-rc.d >/dev/null; then
        invoke-rc.d v-collect restart || true
      else
        /etc/init.d/v-collect restart || true
      fi
    fi
    echo " OK"

	fi
	;;
esac
